=== umsl-ispc/ispcsite/meetings/2002-03-21/xmltalk/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book (title, author+, isbn, subject*, publisher, date?)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== umsl-ispc/ispcsite/meetings/2002-03-21/xmltalk/bookwithdtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<title>XSLT</title>
	<author>Doug Tidwell</author>
	<isbn>0-596-00053-7</isbn>
	<subject>XSLT</subject>
	<subject>XML</subject>
	<publisher>O'Reilly</publisher>
	<date>02/09/2002</date>
</book>
